#-- .Makefile.toml ---

# ==============================================================================
# Makefile.toml for cargo-make
#
# Cargo Make is a task runner for Rust projects that allows you to define custom tasks
# in a simple TOML format. It provides a way to automate common development workflows
# like building, testing and serving documentation.
#
# This file defines tasks for the personal-ledger-backend project.
#
# Usage: cargo make <task-name>
# Example: cargo make docs-serve
# -----------------------------------------------------------------------------

[tasks.docs-rustdoc]
description = "Build Rust docs (with RUSTDOCFLAGS to set asset root)"
env = { RUSTDOCFLAGS = "-Z unstable-options --static-root-path /rust-docs" }
command = "sh"
args = ["-c", "cargo +nightly doc --no-deps --target-dir docs/rustdoc"]

[tasks.docs-mdbook]
description = "Build mdBook documentation"
command = "sh"
args = ["-c", "mdbook build"]

[tasks.docs-build]
description = "Build all documentation"
dependencies = ["docs-rustdoc", "docs-mdbook"]

[tasks.docs-serve]
install_crate = "mdbook"
description = "Serve mdBook documentation on port 8001"
command = "mdbook"
args = ["serve", "--port", "8001"]

## Update git submodules in repository
## $ git submodule update --recursive --remote
## $ cargo make submodules
[tasks.submodules]
command = "git"
args = ["submodule", "update", "--recursive", "--remote"]
