site_name: Personal Ledger Backend
theme:
  name: material
  palette:
    primary: blue
    accent: blue
nav:
  - Home: index.md
  - API Documentation: api.md
plugins:
  - search
markdown_extensions:
  - codehilite
  - toc:
      permalink: true
